@hostname = localhost
@port = 8080
@host = {{hostname}}:{{port}}
@baseurl = http://{{host}}/api
@url = {{baseurl}}/userWorkout

@token = eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJkZXYxMC11c2Vycy1hcGkiLCJzdWIiOiJzYWxseUBqb25lcy5jb20iLCJpZCI6IjllNWQ5MjcyLWFmNGYtMTFlYi04MzY4LTAyNDJhYzExMDAwMiIsInJvbGVzIjoiVVNFUiIsImV4cCI6MTYzMDQxOTY2OH0.njPCyR8fRVIn_dBaM8O5MEEZCL-bqJYWZ6ywjByVttc


###

GET {{url}}/1 HTTP/1.1
Authorization: Bearer {{token}}
//find workouts by user ID

###

POST {{url}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}
//create user workout

{
   "userId" : 1,
   "workoutId" : 1,
   "workoutDate" : "2021-08-25"
}
